version: '3.8'

services:
  subscription_manager:
    build: 
      context: ./subscription_manager
      dockerfile: Dockerfile
    container_name: subscription_manager
    ports: 
      - "5004:5004"
    environment:
      - MONGO_URL=mongodb://mongo:27017/subscriptions
    depends_on:
      - mongo

  logger_service:
    build: 
      context: ./logger_service
      dockerfile: Dockerfile
    container_name: logger_service
    ports: 
      - "5006:5006"
    environment:
      - MONGO_URL=mongodb://mongo:27017/subscriptions
    depends_on:
      - mongo

  prediction_service:
    build: 
      context: ./prediction_service
      dockerfile: Dockerfile
    container_name: prediction_service
    ports: 
      - "5005:5005"

  api_service:
    build: 
      context: ./api_service
      dockerfile: Dockerfile
    container_name: api_service
    environment:
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    ports: 
      - "5000:5000"
    depends_on:
      - logger_service
      - subscription_manager
      - memcached
      - prediction_service

  mongo:
    image: mongo:latest
    container_name: mongo_container
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=subscriptions
    volumes:
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  memcached:
    image: memcached:latest
    container_name: memcached
    hostname: memcached
    ports:
      - "11211:11211"
    command: memcached -m 64